name: pattern_walking

### planner environment settings ###############################################

# discretization of continuous space
cell_size: &cell_size 0.01 # cell size in meters

resolution:
  x: *cell_size
  y: *cell_size
  z: *cell_size
  num_angle_bins: 72 # bins per full turn (0-360°)

# parameters for heuristics
max_heuristic_value: 1000.0
heuristic_scale: 1.0

# maximum risk before state will be discarded
max_risk: 1.0

### planner settings ###########################################################

plugin_set: thor_mang_default

# define the planner of choice provided by the SBPL package
# - ARAPlanner
# - ADPlanner
# - RSTARPlanner
planner_type: ARAPlanner

# search until a specific time limit is reached or first solution is found
search_until_first_solution: False

max_planning_time: 10.0 # default max planning time if not given by request
initial_epsilon: 8.0
decrease_epsilon: 0.2

forward_search: True

### Planning parameterization for a large humanoid, similar to ASIMO or HRP-2 ##
# used for foot contact support collision check
foot_contact_support:
  min_sampling_steps_x: 6
  min_sampling_steps_y: 4
  max_sampling_steps_x: 32
  max_sampling_steps_y: 24
  max_intrusion_z: 0.01
  max_ground_clearance: 0.02
  minimal_support: 0.85

collision_check:
  # collision check mask (binary encoded)
  # - 1 feet
  # - 2 upper body
  # - 4 foot contact support
  collision_check_mask: 3

  # footstep collision check accuracy
  # - 0 (just the circumcircle of the foot)
  # - 1 (just the incircle of the foot)
  # - 2 (circumcircle and incircle recursivly checked for the whole foot)
  collision_check_accuracy: 2

sway_duration: 0.0
step_duration: 1.0
swing_height:  0.1

### misc ###################################################################
feedback_rate: 10.0 # [Hz]
threads: 4
jobs_per_thread: 100
