pattern_generator:
    update_rate: 10 # [Hz]
    number_of_steps_needed: 6
    republish_complete_step_plan: False

joystick:
    thresh_x:       0.40
    thresh_y:       0.40
    thresh_yaw:     0.20
    sensivity_x:    1.00
    sensivity_y:    1.00
    sensivity_yaw:  1.00
    min_vel_x:     -0.05 # [m/step] min delta x per step
    max_vel_x:      0.10 # [m/step] max delta x per step
    min_vel_y:     -0.07 # [m/step] min delta y per step
    max_vel_y:      0.07 # [m/step] max delta y per step
    min_vel_yaw:   -3.00 # [deg/step] min delta yaw per step
    max_vel_yaw:    3.00 # [deg/step] max delta yaw per step
    min_acc_x:     -0.01 # [m/step^2] min acceleration in x per step
    max_acc_x:      0.02 # [m/step^2] max acceleration in x per step
    min_acc_y:     -0.02 # [m/step^2] min acceleration in y per step
    max_acc_y:      0.02 # [m/step^2] max acceleration in y per step
    min_acc_yaw:   -0.50 # [deg/step^2] min acceleration in yaw per step
    max_acc_yaw:    0.50 # [deg/step^2] max acceleration in yaw per step
