robot_model:
  description:
    ### upper body settings ########################################################
    base:
      size: {x: 0.7, y: 1.1, z: 1.5} # [m]
      frame_id: "pelvis"
      offset: {x: -0.1, y: 0.00, z: 0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad], transformation from center to shifted frame
    
    ### foot settings ##############################################################
    base_foot: &base_foot
      - shape: "CUBOID" # CUBOID, SPHERICAL
        size: {x: 0.22, y: 0.15, z: 0.015} # [m]

    feet:
      - <<: *base_foot
        idx: 0
        name: "LEFT_FOOT"
        frame_id: "l_leg_foot_link"
        # position of planner foot frame (center of sole) given in robot's "foot" tf frame
        offset: {x:  0.00, y:  0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        neutral_stance: {x:  0.00, y:  0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 0.0, g: 1.0, b: 0.0, a: 0.6}
          mesh_resource: "package://thormang3_description/meshes/robotis_l_leg_foot.stl"
          # position of mesh frame given in foot sole frame
          mesh_offset: {x:  0.00, y:  0.00, z:  0.0204, roll:  0.00, pitch:  0.00, yaw:  0.00}
          mesh_scale: 0.001

      - <<: *base_foot
        idx: 1
        name: "RIGHT_FOOT"
        frame_id: "r_leg_foot_link"
        # position of planner foot frame (center of sole) given in robot's "foot" tf frame
        offset: {x:  0.00, y: -0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        neutral_stance: {x:  0.00, y: -0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}
        vis:
          color: {r: 1.0, g: 0.0, b: 0.0, a: 0.6}
          mesh_resource: "package://thormang3_description/meshes/robotis_r_leg_foot.stl"
          # position of mesh frame given in foot sole frame
          mesh_offset: {x:  0.00, y:  0.00, z:  0.0204, roll:  0.00, pitch:  0.00, yaw:  0.00}
          mesh_scale: 0.001
