robot_model:
  description:
    ### upper body settings ########################################################
    base:
      size: {x: 0.7, y: 1.1, z: 1.5} # [m]
      frame_id: "pelvis"
      offset: {x: -0.1, y: 0.00, z: 0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad], transformation from center to shifted frame
    
    ### foot settings ##############################################################
    base_foot: &base_foot
      - size:
          {x: 0.22, y: 0.15, z: 0.015} # [m]
        neutral_stance:
          {x:  0.00, y:  0.00, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]

    feet:
      - <<: *base_foot
        idx: 0
        name: "LEFT_FOOT"
        frame_id: "l_leg_foot_link"
        offset: # position of planner foot frame (center of sole) given in robot's "foot" tf frame
          {x:  0.00, y:  0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        neutral_stance:
          {x:  0.00, y:  0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}

      - <<: *base_foot
        idx: 1
        name: "RIGHT_FOOT"
        frame_id: "r_leg_foot_link"
        offset: # position of planner foot frame (center of sole) given in robot's "foot" tf frame
          {x:  0.00, y: -0.0155, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00} # 3x[m] 3x[rad]
        neutral_stance:
          {x:  0.00, y: -0.1085, z:  0.00, roll:  0.00, pitch:  0.00, yaw:  0.00}

