plugin_sets:
  thor_mang_default:
    # GaitGeneratorPlugin
    bipedal_gait_generator: none

    # StateGeneratorPlugin
    reachability_state_generator:
      params:
        reachability_polygons: &reachability_polygons
          base_polygon: &base_polygon
            - x: [ 0.00, -0.10, -0.08, -0.05,  0.05,  0.10,  0.13]
              y: [-0.04, -0.04,  0.03,  0.08,  0.08,  0.03, -0.04]
              yaw: [-0.05, 0.30]

          feet:
            - <<: *base_polygon
              idx: 0 # left

            - <<: *base_polygon
              idx: 1 # right
              mirror_y: True
              mirror_yaw: True

    # StepPlanMsgPlugin
    step_plan_msg_plugin: none
    #thor_mang_step_plan_msg_plugin: none

    # ReachabilityPlugins
    reachability_polygon:
      params:
        reachability_polygons: *reachability_polygons

    # StepCostEstimatorPlugins
    const_step_cost_estimator:
      params:
        step_cost: &step_cost 0.1
    euclidean_step_cost_estimator: none
    ground_contact_step_cost_estimator: none

    # HeuristicPlugins
    euclidean_heuristic: none
    dynamics_heuristic:
      params:
        max_body_vel: 0.0
        max_body_acc: 0.0
    step_cost_heuristic:
      params:
        step_cost: *step_cost
        diff_angle_cost: 0.05
        max_step_dist_x: 0.13
        max_step_dist_y: 0.08

    # PostProcessPlugins
    step_dynamics_post_process: none

    # CollisionCheckPlugins
    2_upper_body_grid_map_model:
      import: upper_body_grid_map_model
      params:
        collision_check_flag: 2 # Upper Body
        grid_map_topic: /body_level_grid_map
    3_foot_grid_map_model:
      import: foot_grid_map_model
      params:
        collision_check_flag: 1 # Foot
        grid_map_topic: /ground_level_grid_map

    # TerrainModelPlugins
    1_terrain_model:
      import: terrain_model
      params:
        collision_check_flag: 4 # Foot Contact Support
        terrain_model_topic: /terrain_model
